config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

# Swagger docs
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Favorite Things API",
      default_version='v1',
      description="BriteCore Software Engineer Challenge",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Default template routes
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Rest Framework
    path("api/v1/", include("things.urls", namespace="things")),
    # Django Rest Framework Swagger API Documentation
    path("api/docs/", schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("favorite_things.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

favorite_things/users/urls.py
from django.urls import path

from favorite_things.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

things/urls.py
from django.urls import include, path
from rest_framework import routers
from .views import FavoriteThingView, FavoriteThingCategoryView

app_name = "things"

router = routers.SimpleRouter()
router.register(r"things", FavoriteThingView)
router.register(r"things-category", FavoriteThingCategoryView)

urlpatterns = router.urls

favorite_things/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

things/models.py
from django.db import models

# Model Additions
from django.core.validators import MinLengthValidator
from django.contrib.postgres.fields import JSONField

# Django Audit App
from simple_history.models import HistoricalRecords

# Django Signals
from django.db.models.signals import pre_save
from django.dispatch import receiver


class FavoriteThing(models.Model):
    """
        Model to store Favorite Things, fields are:
        title (required),
        description (optional, min=10),
        ranking (required & unique integer),
        metadata (optional & contains key/value attributes),
        category (required selection from FavoriteThingCategory Model),
        created / modified date (required & automatically added fields),
        audit log (required, automic & contains string list of changes to data)
    """
    title = models.CharField(max_length=255)
    description = models.CharField(validators=[MinLengthValidator(10)],
                                   max_length=512, null=True, blank=True)
    ranking = models.IntegerField()
    metadata = JSONField(null=True, blank=True)
    category = models.ForeignKey('FavoriteThingCategory',
                                 on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now=True)
    modified_date = models.DateTimeField(auto_now=True)
    audit_log = HistoricalRecords()

    class Meta:
        verbose_name = "Favorite Thing"
        verbose_name_plural = "Favorite Things"
        ordering = ['title']

    def __str__(self):
        return self.title


class FavoriteThingCategory(models.Model):
    """
        Model to store Favorite Thing Categories: name
    """
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Favorite Thing Category"
        verbose_name_plural = "Favorite Thing Categories"
        ordering = ['name']

    def __str__(self):
        return self.name

        
@receiver(pre_save, sender=FavoriteThing)
def update_rankings(sender, instance, *args, **kwargs):
    """
        Updates Ranking across model instances in same category
        - if new ranking does not exist : do nothing
        - else : re-order instance
    """
    category_things = FavoriteThing.objects.filter(
                category=instance.category).order_by('ranking')
    current_rankings = [f.ranking for f in category_things]
    if (instance.ranking in current_rankings):
        instance.ranking += 1
        instance.save()

favorite_things/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

favorite_things/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

things/views.py
from rest_framework import viewsets
from .models import FavoriteThing, FavoriteThingCategory
from .serializers import (FavoriteThingSerializer, 
        FavoriteThingCategorySerializer)

class FavoriteThingView(viewsets.ModelViewSet):
    """
        Handles API CRUD Actions for FavoriteThing Model Serializer
    """
    queryset = FavoriteThing.objects.all()
    serializer_class = FavoriteThingSerializer


class FavoriteThingCategoryView(viewsets.ModelViewSet):
    """
        Handles API CRUD Actions for FavoriteThingCategory Model Serializer
    """
    queryset = FavoriteThingCategory.objects.all()
    serializer_class = FavoriteThingCategorySerializer

favorite_things/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}favorite-things{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">favorite-things</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

favorite_things/templates/pages/about.html
<html>
  <title>Favorite Things</title>
  <body>
    <h1 id="favorite-things">Favorite Things</h1>
    <p>&gt; BriteCore Software Engineer Challenge</p>
    <h2 id="basic-user-flow">Basic User Flow</h2>
    <ul>
      <li>
        <a href="https://timbritecore.herokuapp.com/api/docs"
          >Explore Backend API Docs</a
        >
      </li>
      <li>
        <a href="https://wonderful-clarke-466ff3.netlify.com/"
          >Visit FrontEnd</a
        >
      </li>
      <li>
        On frontend, to <em>add new Favorite Thing</em>, click the button with
        text: <em>*Click to add new favorite item</em>
        <ul>
          <li>Enter values for fields</li>
          <li>Search/Select for Category</li>
          <li>If needed, add new Category</li>
        </ul>
      </li>
      <li>
        On frontend, to <em>edit Favorite Thing</em>, click edit button on the
        table for desired thing to edit.
      </li>
      <li>
        On frontend, to <em>delete Favorite Thing</em>, click delete button on
        the table for desired thing to edit.
      </li>
    </ul>
    <h2 id="deliverables">Deliverables</h2>
    <h3 id="backend-data">Backend Data</h3>
    <ul>
      <li>
        Python Models containing the ORM classes:
        <a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/things/models.py">here</a>
      </li>
      <li>
        Entity Relationship Diagram:
        <a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/favorite-things-erd.png">here</a>
      </li>
      <li>
        JSON Representation of Models: <a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/model-json.png">here</a>
      </li>
    </ul>
    <h3 id="backend-api">Backend API</h3>
    <ul>
      <li><a href="https://gitlab.com/Timtech4u/favorite_things/tree/master/things">API Codes</a></li>
      <li>
        Django REST Framework Class Based Views:
        <a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/things/views.py">here</a>
      </li>
      <li>
        Deployed REST API Documentation:
        <a href="https://timbritecore.herokuapp.com/api/docs">here</a>
      </li>
    </ul>
    <h3 id="frontend">Frontend</h3>
    <ul>
      <li><a href="https://gitlab.com/Timtech4u/favorite_things/master/frontend">Codes</a></li>
      <li><strong>Screenshots</strong> <a href="#screenshots">here</a></li>
      <li>
        Deployed Single Page Application:
        <a href="https://wonderful-clarke-466ff3.netlify.com/">here</a>
      </li>
    </ul>
    <h2 id="technologies-used">Technologies Used</h2>
    <h3 id="backend">Backend</h3>
    <ul>
      <li>Django with Cookiecutter</li>
      <li>Django Rest Framework</li>
      <li>Ubuntu O.S.</li>
      <li>Python 3.7 with PEP8</li>
      <li>PostgreSQL database</li>
      <li>Heroku deployment</li>
    </ul>
    <h3 id="frontend">Frontend</h3>
    <ul>
      <li>Vue.js</li>
      <li>ESLint</li>
      <li>Vuex State Managment</li>
      <li>Axios</li>
      <li>Element UI</li>
      <li>Netlify&#39;s deployment</li>
    </ul>
    <h2 id="-tests-things-tests-py-"><a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/things/tests.py">Tests</a></h2>
    <ul>
      <li>
        To Test Favorite Thing Category Create:
        <code
          >python manage.py test
          things.tests.TestThingsCategory.test_create</code
        >
      </li>
      <li>
        To Test Favorite Thing Category List:
        <code
          >python manage.py test things.tests.TestThingsCategory.test_list</code
        >
      </li>
      <li>
        To Test Favorite Thing Create:
        <code
          >python manage.py test
          things.tests.TestFavoriteThings.test_create</code
        >
      </li>
      <li>
        To Test Favorite Thing List:
        <code
          >python manage.py test things.tests.TestFavoriteThings.test_list</code
        >
      </li>
      <li>
        To Test Favorite Thing Delete:
        <code
          >python manage.py test
          things.tests.TestFavoriteThings.test_delete</code
        >
      </li>
    </ul>
    <h2 id="screenshots">Screenshots</h2>
    <h3 id="add-new-favorite-thing">Add new Favorite Thing</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/new.png" alt="new" /></p>
    <h3 id="list-of-favorite-things">List of Favorite Things</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/list.png" alt="list" /></p>
    <h3 id="favorite-things-detail">Favorite Things Detail</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/detail.png" alt="detail" /></p>
    <h3 id="favourite-thing-audit-log">Favourite Thing Audit Log</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/log.png" alt="log" /></p>
    <h3 id="edit-favorite-thing">Edit Favorite Thing</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/edit.png" alt="edit" /></p>
    <h3 id="category">Category</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/category.png" alt="category" /></p>
  </body>
</html>

favorite_things/templates/pages/home.html
<html>
  <title>Favorite Things</title>
  <body>
    <h1 id="favorite-things">Favorite Things</h1>
    <p>&gt; BriteCore Software Engineer Challenge</p>
    <h2 id="basic-user-flow">Basic User Flow</h2>
    <ul>
      <li>
        <a href="https://timbritecore.herokuapp.com/api/docs"
          >Explore Backend API Docs</a
        >
      </li>
      <li>
        <a href="https://wonderful-clarke-466ff3.netlify.com/"
          >Visit FrontEnd</a
        >
      </li>
      <li>
        On frontend, to <em>add new Favorite Thing</em>, click the button with
        text: <em>*Click to add new favorite item</em>
        <ul>
          <li>Enter values for fields</li>
          <li>Search/Select for Category</li>
          <li>If needed, add new Category</li>
        </ul>
      </li>
      <li>
        On frontend, to <em>edit Favorite Thing</em>, click edit button on the
        table for desired thing to edit.
      </li>
      <li>
        On frontend, to <em>delete Favorite Thing</em>, click delete button on
        the table for desired thing to edit.
      </li>
    </ul>
    <h2 id="deliverables">Deliverables</h2>
    <h3 id="backend-data">Backend Data</h3>
    <ul>
      <li>
        Python Models containing the ORM classes:
        <a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/things/models.py">here</a>
      </li>
      <li>
        Entity Relationship Diagram:
        <a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/favorite-things-erd.png">here</a>
      </li>
      <li>
        JSON Representation of Models: <a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/model-json.png">here</a>
      </li>
    </ul>
    <h3 id="backend-api">Backend API</h3>
    <ul>
      <li><a href="https://gitlab.com/Timtech4u/favorite_things/tree/master/things">API Codes</a></li>
      <li>
        Django REST Framework Class Based Views:
        <a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/things/views.py">here</a>
      </li>
      <li>
        Deployed REST API Documentation:
        <a href="https://timbritecore.herokuapp.com/api/docs">here</a>
      </li>
    </ul>
    <h3 id="frontend">Frontend</h3>
    <ul>
      <li><a href="https://gitlab.com/Timtech4u/favorite_things/master/frontend">Codes</a></li>
      <li><strong>Screenshots</strong> <a href="#screenshots">here</a></li>
      <li>
        Deployed Single Page Application:
        <a href="https://wonderful-clarke-466ff3.netlify.com/">here</a>
      </li>
    </ul>
    <h2 id="technologies-used">Technologies Used</h2>
    <h3 id="backend">Backend</h3>
    <ul>
      <li>Django with Cookiecutter</li>
      <li>Django Rest Framework</li>
      <li>Ubuntu O.S.</li>
      <li>Python 3.7 with PEP8</li>
      <li>PostgreSQL database</li>
      <li>Heroku deployment</li>
    </ul>
    <h3 id="frontend">Frontend</h3>
    <ul>
      <li>Vue.js</li>
      <li>ESLint</li>
      <li>Vuex State Managment</li>
      <li>Axios</li>
      <li>Element UI</li>
      <li>Netlify&#39;s deployment</li>
    </ul>
    <h2 id="-tests-things-tests-py-"><a href="https://gitlab.com/Timtech4u/favorite_things/blob/master/things/tests.py">Tests</a></h2>
    <ul>
      <li>
        To Test Favorite Thing Category Create:
        <code
          >python manage.py test
          things.tests.TestThingsCategory.test_create</code
        >
      </li>
      <li>
        To Test Favorite Thing Category List:
        <code
          >python manage.py test things.tests.TestThingsCategory.test_list</code
        >
      </li>
      <li>
        To Test Favorite Thing Create:
        <code
          >python manage.py test
          things.tests.TestFavoriteThings.test_create</code
        >
      </li>
      <li>
        To Test Favorite Thing List:
        <code
          >python manage.py test things.tests.TestFavoriteThings.test_list</code
        >
      </li>
      <li>
        To Test Favorite Thing Delete:
        <code
          >python manage.py test
          things.tests.TestFavoriteThings.test_delete</code
        >
      </li>
    </ul>
    <h2 id="screenshots">Screenshots</h2>
    <h3 id="add-new-favorite-thing">Add new Favorite Thing</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/new.png" alt="new" /></p>
    <h3 id="list-of-favorite-things">List of Favorite Things</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/list.png" alt="list" /></p>
    <h3 id="favorite-things-detail">Favorite Things Detail</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/detail.png" alt="detail" /></p>
    <h3 id="favourite-thing-audit-log">Favourite Thing Audit Log</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/log.png" alt="log" /></p>
    <h3 id="edit-favorite-thing">Edit Favorite Thing</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/edit.png" alt="edit" /></p>
    <h3 id="category">Category</h3>
    <p><img src="https://gitlab.com/Timtech4u/favorite_things/raw/master/screenshots/category.png" alt="category" /></p>
  </body>
</html>

favorite_things/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

favorite_things/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}